name:                exact-cover
version:             0.1.0.0
github:              "zerolfx/exact-cover"
license:             BSD3
author:              "zerol"
maintainer:          "zerolfx0@gmail.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zerolfx/exact-cover#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -eventlog

executables:
  exact-cover-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - exact-cover
